# ====================================================================================
# azure-pipelines.yml Restore, Build, Test, Pack, Push
# ====================================================================================
trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  dotnetVersion: '8.0.x'

  majorVersion: '12'
  minorVersion: '0'

  patchVersion: $[ counter( format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0) ]
  preReleaseSuffix:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')  }}:
    value: ''
  ${{ else }}:
    value: '-beta' 
    
  buildVersion: $[ format('{0}.{1}.{2}{3}', variables['majorVersion'], variables['minorVersion'], variables['patchVersion'], variables['preReleaseSuffix']) ]
  buildConfiguration: 'Release'

  JFrogUser: 'user-hq-idf'
  JFrogPassword: '** Retrieved from KeyVault **'
  JFrogNuGetRepositoryURL: 'https://ayvens.jfrog.io/artifactory/api/nuget/v3/nuget-virtual-hq-idf'
  JfrogNugetPrivateRepositoryURL: 'https://ayvens.jfrog.io/artifactory/api/nuget/v3/nuget-private-hq-idf'

stages:
  - stage: build
    displayName: Build
    
    jobs:    
    - job: build
      displayName: Restore, Build, Test, Pack, Push
  
      steps:
        # ====================================================================================
        # Override Build Number
        # ====================================================================================
        - powershell: |
            $version = "$(buildVersion)"
            Write-Host "##vso[build.updatebuildnumber]$version"
            Write-Host "##vso[task.setvariable variable=BuildVersion]$version"
          displayName: 'Setup Version'
        # ====================================================================================
        # Fetch Build Prerequisites
        # ====================================================================================
        - task: UseDotNet@2
          displayName: 'Install .NET SDK'
          inputs:
            version: $(dotnetVersion)
        - task: DownloadPackage@1
          displayName: Download Package Microsoft.CodeCoverage
          inputs:
            feed: /1637fbec-290e-48c4-b3e5-bf765ea3ddb4
            view: 32d74934-ac69-473a-bed5-d87aaffe4d41
            definition: f1a620f7-2e9e-4bb4-812b-c6b1ea6e06f3
            version: 16.1.1
        # ====================================================================================
        # Configure Nuget Feeds
        # ====================================================================================
        - task: AzureKeyVault@2
          displayName: 'Fetch JFrogPassword From KeyVault'
          inputs:
            azureSubscription: 'OC-HQ-IDF-Private-DEV data'
            KeyVaultName: 'ald-oc-idf-dev-we-vault'
            SecretsFilter: 'JFrogPassword'
        - task: DeleteFiles@1
          displayName: 'Delete NuGet.Config'
          inputs:
            sourceFolder: $(Build.SourcesDirectory)
            contents: '**/NuGet.Config'
        # ====================================================================================
        # Prepare SonarQube
        # ====================================================================================
        - task: SonarSource.sonarqube.15B84CA1-B62F-4A2A-A403-89B77A063157.SonarQubePrepare@8
          displayName: 'Prepare SonarQube Analysis'
          inputs:
            SonarQube: f87d359d-181a-4c0a-a620-9cf29923fe19
            projectKey: $(Build.Repository.Name)
            projectName: $(Build.Repository.Name)
            projectVersion: $(Build.BuildNumber)
        # ====================================================================================
        # Assembly-Info
        # ====================================================================================
        - task: Assembly-Info-NetCore@3
          displayName: 'Setup Assembly Manifest'
          inputs:
            InsertAttributes: true
            VersionNumber: '$(buildVersion).0'
            FileVersionNumber: '$(buildVersion)'
            InformationalVersion: '$(buildVersion)'
            PackageVersion: '$(buildVersion)'
            LogLevel: 'verbose'
            AddBuildTag: 'v$(buildVersion)'
            DisableTelemetry: true
        # ====================================================================================
        # Restore, Build, Test
        # ====================================================================================
        - powershell: |
              Write-Host "NuGet sources before the operation..."
              dotnet nuget list source
              Write-Host "Clearing existing NuGet sources..."
              dotnet nuget remove source "nuget.org"
              dotnet nuget remove source "PLASMA"
              dotnet nuget remove source "PLASMAL"
              Write-Host "Adding source: [JFrog] at [$(JFrogNuGetRepositoryURL)] with username [$(JFrogUser)]"
              dotnet nuget add source $(JFrogNuGetRepositoryURL) --name JFrog --username $(JFrogUser) --password $(JFrogPassword)
              Write-Host "NuGet sources after the operation..."
              dotnet nuget list source
              Write-Host "Restoring projects..."
              Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter *.csproj |
                ForEach-Object {
                    Write-Host "Restoring $($_.FullName)"
                    dotnet restore $_.FullName 
                }
              Write-Host "Restore complete."
          displayName: 'dotnet restore'
        - task: DotNetCoreCLI@2
          displayName: dotnet build
          inputs:
            projects: '**/*.csproj'
            arguments: --configuration $(buildConfiguration) --no-restore
            configurationToPack: Release
        - task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: test
            projects: '**/*[Uu]nit[Tt]est*.csproj'
            arguments: --configuration $(buildConfiguration) --collect "Code coverage" --no-restore --no-build
            configurationToPack: Release
        # ====================================================================================
        # Collect Test + Coverage Files
        # ====================================================================================
        - powershell: |
            robocopy "$(Agent.TempDirectory)" "$(Agent.BuildDirectory)\TestResults" "*.trx" /s
            robocopy "$(Agent.TempDirectory)" "$(Agent.BuildDirectory)\TestResults" "*.coverage" /s
            $codeCoverage = Get-ChildItem "$(Agent.BuildDirectory)" -Recurse -Filter "CodeCoverage.exe"
            $codeCoverageExe = $codeCoverage.FullName
            Write-Host $codeCoverageExe 
            Get-ChildItem "$(Agent.BuildDirectory)\TestResults" -Recurse -Filter "*.coverage" | % {
              $guid = New-Guid
              $output = "$(Agent.BuildDirectory)\TestResults\$guid.coveragexml"
              $coverageFile = $_.FullName
              "Analyse '$coverageFile' with output '$output'..."
              & $codeCoverageExe analyze /output:$output $coverageFile
            }  
          displayName: 'Copy Test and Coverage Files'
        # ====================================================================================
        # Publish SonarQube Results and Quality Gate Results
        # ====================================================================================
        - task: SonarSource.sonarqube.6D01813A-9589-4B15-8491-8164AEB38055.SonarQubeAnalyze@8
          displayName: 'Run Code Analysis'
        - task: SonarSource.sonarqube.291ed61f-1ee4-45d3-b1b0-bf822d9095ef.SonarQubePublish@8
          displayName: 'Publish Quality Gate'
          inputs:
            pollingTimeoutSec: 1200
        - task: SimondeLang.sonar-buildbreaker.sonar-buildbreaker.sonar-buildbreaker@8
          displayName: 'Break Build on Quality Gate'
          inputs:
            SonarQube: f87d359d-181a-4c0a-a620-9cf29923fe19
        # ====================================================================================
        # Pack and Push Nuget Packages
        # ====================================================================================
        - task: DotNetCoreCLI@2
          displayName: 'dotnet pack'
          inputs:
            command: pack
            verbosityRestore: Detailed
            configurationToPack: Release
            nobuild: true
            versioningScheme: byBuildNumber
            verbosityPack: Detailed
        - powershell: |
            dotnet nuget list source
            dotnet nuget add source $(JFrogNuGetPrivateRepositoryURL) --name JFrogPrivate --username $(JFrogUser) --password $(JFrogPassword)
            dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg --source JFrogPrivate
          displayName: 'dotnet push'